---
title: "Problem 2"
author: "Zicheng Wang"
date: "2024-09-16"
output: github_document
---

Load necessary packages:
```{r setup}
library(tidyverse)
```

Create a data frame:
```{r df_create}
df <- tibble(
  sample_normal = rnorm(10, mean = 0, sd = 1),
  sample_logic = sample_normal > 0,
  sample_char = sample(letters, 10),
  sample_level = factor(sample(c("Level1", "Level2", "Level3"), 10, replace = TRUE))
)
```

Display the data frame to inspect:  
```{r}
print(df)
```

Calculate means of each variable in the data frame:  
```{r}
mean(df %>% pull(sample_normal))
mean(df %>% pull(sample_logic))
mean(df %>% pull(sample_char))
mean(df %>% pull(sample_level))
```

Change those type of variables that cannot calculate mean into numeric type:  
```{r eval = FALSE}
df$sample_logic <- as.numeric(df$sample_logic)
df$sample_char <- as.numeric(df$sample_char)
df$sample_level <- as.numeric(df$sample_level)
```
First two lines returned following message: `Warning: NAs introduced by coercion`, the last line performed without warnings.


